	/*Create Usre Difine Fuction Name Print Which Used to Print Line
	on Ouput Window*/

# include<iostream.h>
# include<conio.h>
void Printline();
void Printline()
{
	int i;
	for(i=1;i<50;i++)
	{
		cout<<".";
	}
	cout<<"\n";
}
void main()
{
	clrscr();
	Printline();
	cout<<"\n Thanks & have a Nice day.....";
	cout<<"\n";
	Printline();
	cout<<"\n Thanks & have a Nice day.....";
	cout<<"\n";
	Printline();
	cout<<"\n Thanks & have a Nice day.....";
	cout<<"\n";
	Printline();
	getch();
}
